# TODO: Envoyer tous les nouveaux fichiers de configuration sur github
colors.draw_bold_text_with_bright_colors = true
import = ["~/.config/alacritty/rose-pine/rose-pine.toml"]

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"
